### ISSUE TITLE
Not working after uploading json. I don't get any report. thanks

### ISSUE THREAD

**Issue by CamiloUno** [eric1234/stats_for_everdo#1]

**Comment by CamiloUno** [comment]
Now I tried from home network and it is fine.

**Comment by eric1234** [comment]
Glad you got it working. Will close this issue then. It is a bit slow if you have many years of tasks. There are ways to speed it up (load into a DB, use web workers, etc) but overall that complication hasn't been worth it for me since it was meant as just a quick tool I developed so slow is good enough for me.

**Comment by CamiloUno** [comment]
Thanks for your effort to help me. Now working perfectly.
